version: '3'
services:
  fire-app:
    # build: .
    image: "repo.treescale.com/tomwillisgd/minizinc-python-nodejs:latest"
    # image: "minizinc/minizinc:latest"
    # image: "nikolaik/python-nodejs:python3.8-nodejs12"
    container_name: fire-app-container
    volumes:
    - ../:/workspace:cached
    - node_modules:/workspace/ui/node_modules
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  node_modules: