version: '3'
services:
  fire-app:
    # build: .
    image: "repo.treescale.com/fire-app-dev/minizinc-python-nodejs:latest"
    container_name: fire-app-container
    volumes:
    - ../:/workspace:cached
    - node_modules:/workspace/ui/node_modules
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  node_modules: